name: .NET CI/CD with Docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Build the .NET application
  dotnet-build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: "Test123."
        ports:
          - 1433:1433

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.102

      - name: Restore dependencies
        run: dotnet restore

      - name: Wait for SQL Server to start
        run: |
          sleep 30  # Wait for SQL Server to fully start

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run Tests
        run: dotnet test  # Add this step to run tests

      - name: Publish the application (Package)
        run: dotnet publish -c Release -o ./out  # Publish the application to the 'out' folder

      - name: Upload published app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: librarybook-app
          path: ./out  # Upload the published output as an artifact

  # Build Docker image and push to Docker Hub
  docker-build:
    runs-on: ubuntu-latest
    needs: dotnet-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download the published app artifact
        uses: actions/download-artifact@v4
        with:
          name: librarybook-app
          path: ./out/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: maxim1040/librarybook:latest
          build-args: ARTIFACT_PATH=./out
